import deepDiff from '../diffing/deepDiff';
import deepMerge from '../diffing/deepMerge';
import Diff from '../diffing/Diff';

describe('diffing', () => {
  it('stress test', () => {
    const value = [
      {
        _id: '621e13c4f88a4c8daa76a452',
        index: 0,
        guid: 'cbff3681-d1ea-4097-a081-720d8fcbe03d',
        isActive: false,
        balance: '$3,179.17',
        picture: 'http://placehold.it/32x32',
        age: 33,
        eyeColor: 'green',
        name: 'Bettie Cabrera',
        gender: 'female',
        company: true,
        email: 'bettiecabrera@austex.com',
        phone: '+1 (810) 403-3341',
        address: '770 Wyona Street, Nettie, Northern Mariana Islands, 9495',
        about:
          'Culpa ullamco ullamco in esse amet consequat sint nulla dolore excepteur in laborum adipisicing eu. Quis dolore aute aliqua eu. Pariatur do irure exercitation incididunt officia cillum eu laborum cupidatat ullamco veniam amet ad minim. Sint deserunt consequat commodo culpa ad. Culpa consectetur incididunt sunt commodo aute amet pariatur proident reprehenderit occaecat. Tempor ex laborum est adipisicing fugiat. Cillum non ad voluptate cupidatat quis pariatur nulla veniam.\r\n',
        registered: '2019-04-06T08:13:50 -08:00',
        latitude: 36.497975,
        longitude: 59.878953,
        tags: [
          'ullamco',
          'Lorem',
          'nostrud',
          'mollit',
          'culpa',
          'minim',
          'tempor',
        ],
        friends: [
          {
            id: 0,
            name: 'Holden Robbins',
          },
          {
            id: 1,
            name: 'Frieda Vargas',
          },
          {
            id: 2,
            name: 'Hendricks Burt',
          },
        ],
        greeting: 'Hello, Bettie Cabrera! You have 3 unread messages.',
        favoriteFruit: 'apple',
      },
      {
        _id: '621e13c4dde1250a88659422',
        index: 1,
        guid: '4b8b0ae2-f263-4258-986b-3d20b866a6b5',
        isActive: true,
        balance: '$1,007.53',
        picture: ['http://placehold.it/32x32'],
        age: 34,
        eyeColor: 'green',
        name: 'Kenya Mendoza',
        gender: 'female',
        company: { a: 'COMVEYER' },
        email: 'kenyamendoza@comveyer.com',
        phone: '+1 (955) 516-2495',
        address: '242 Reed Street, Woodlake, American Samoa, 1631',
        about:
          'Culpa mollit labore exercitation commodo id. Ex ipsum ut aute tempor anim cupidatat commodo. Reprehenderit ea nostrud Lorem sunt in sunt. In cupidatat esse elit commodo nisi est enim.\r\n',
        registered: '2015-10-19T08:18:38 -08:00',
        latitude: -30.092622,
        longitude: -79.992393,
        tags: ['culpa', 'elit', 'fugiat', 'cillum', 'enim', 'ut', 'ut'],
        friends: [
          {
            id: 0,
            name: 'Tonia Fuller',
          },
          {
            id: 1,
            name: 'Effie Lane',
          },
          {
            id: 2,
            name: 'Terrell Maynard',
          },
        ],
        greeting: 'Hello, Kenya Mendoza! You have 7 unread messages.',
        favoriteFruit: 'strawberry',
      },
      {
        _id: '621e13c4cf89a07343302f7c',
        index: 2,
        guid: '7e0cce8c-f88f-462a-9139-e44174b1bf46',
        isActive: true,
        balance: '$2,782.21',
        picture: 'http://placehold.it/32x32',
        age: 38,
        eyeColor: 'blue',
        name: 'Olivia Russell',
        gender: 'female',
        company: 'BALUBA',
        email: 'oliviarussell@baluba.com',
        phone: '+1 (820) 585-3405',
        address: '908 Ocean Parkway, Morgandale, Hawaii, 4181',
        about:
          'Exercitation sit officia proident ullamco. Proident eu ipsum consectetur anim mollit et quis deserunt ea ullamco irure eu adipisicing. Cillum dolore dolore incididunt proident reprehenderit. Cupidatat aute adipisicing sit voluptate qui est commodo veniam elit. Nisi duis et amet minim proident qui nulla minim sunt incididunt duis fugiat tempor. Consectetur qui nulla non ut exercitation ex tempor officia irure sint minim. Cupidatat dolore nulla enim pariatur aute anim do esse labore.\r\n',
        registered: '2020-04-19T02:12:07 -08:00',
        latitude: -25.314924,
        longitude: -170.391531,
        tags: [
          'labore',
          'cillum',
          'qui',
          'non',
          'proident',
          'consequat',
          'mollit',
        ],
        friends: [
          {
            id: 0,
            name: 'Lynne Roach',
          },
          {
            id: 1,
            name: 'Robyn Mendez',
          },
          {
            id: 2,
          },
        ],
        greeting: 'Hello, Olivia Russell! You have 10 unread messages.',
        favoriteFruit: 'strawberry',
      },
      {
        _id: '621e13c4d4ead96ad07722c0',
        index: 3,
        guid: 'ba1e829d-600b-4ce2-bf97-52332e2266ba',
        isActive: false,
        balance: '$3,353.54',
        picture: 'http://placehold.it/32x32',
        age: 39,
        eyeColor: 'brown',
        name: 'Ingram Hale',
        gender: 'male',
        company: 'CIRCUM',
        email: 'ingramhale@circum.com',
        phone: '+1 (866) 416-3109',
        address: '778 Caton Place, Bodega, Alabama, 1410',
        about:
          'Elit et anim sunt adipisicing eiusmod commodo elit. Nisi est duis in quis ipsum et eiusmod sint nulla enim voluptate duis sint. Duis in amet minim eiusmod.\r\n',
        registered: '2020-07-23T03:21:11 -08:00',
        latitude: 76.325808,
        longitude: -130.58796,
        tags: [
          'magna',
          'tempor',
          'consequat',
          'cupidatat',
          'aute',
          'enim',
          'duis',
        ],
        friends: [
          {
            id: 0,
            name: 'Reynolds Reid',
          },
          {
            id: 1,
            name: 'Raymond Golden',
          },
          {
            id: 2,
            name: 'Griffith Sampson',
          },
        ],
        greeting: 'Hello, Ingram Hale! You have 4 unread messages.',
        favoriteFruit: 'apple',
      },
      {
        _id: '621e13c4894b86bc5a824d1b',
        index: 4,
        guid: 'b0f9d5e4-bb52-430a-a6d1-768a5a95c586',
        isActive: false,
        balance: '$1,673.38',
        picture: 'http://placehold.it/32x32',
        age: 22,
        eyeColor: 'green',
        name: 'Alvarez Hurst',
        gender: 'male',
        company: 'REPETWIRE',
        email: 'alvarezhurst@repetwire.com',
        phone: '+1 (871) 468-2280',
        address: '831 Riverdale Avenue, Taycheedah, Wyoming, 4433',
        about: '??',
        registered: '2021-01-03T09:13:10 -08:00',
        latitude: 53.069786,
        longitude: 69.564384,
        tags: [
          'elit',
          'aliqua',
          'ad',
          'est',
          'reprehenderit',
          'laborum',
          'consectetur',
        ],
        friends: [
          {
            id: 0,
            name: 'Hewitt Hammond',
          },
          {
            id: 1,
            name: 'Sherman Sanchez',
          },
          {
            id: 2,
            name: 'Hess Buck',
          },
        ],
        greeting: 'Hello, Alvarez Hurst! You have 1 unread messages.',
        favoriteFruit: 'apple',
      },
      {
        _id: '621e13c4b68539d982affd75',
        index: 5,
        guid: 'cb863664-8393-4301-ab8b-811ff98421d9',
        isActive: false,
        balance: '$2,859.70',
        picture: 'http://placehold.it/32x32',
        age: 37,
        eyeColor: 'brown',
        name: 'Lily Duran',
        gender: 'female',
        company: 'PREMIANT',
        email: 'lilyduran@premiant.com',
        phone: '+1 (915) 600-3424',
        address: '136 Himrod Street, Hoagland, Rhode Island, 8520',
        about:
          'Occaecat quis nostrud Lorem eiusmod excepteur enim. Ea in sit amet in incididunt Lorem quis aute. Mollit labore id minim reprehenderit qui reprehenderit et nisi elit in nisi irure Lorem ipsum. Nisi ad ex quis proident proident sint et nulla ex culpa ex ex nostrud irure. Nostrud reprehenderit sunt duis eiusmod magna reprehenderit et cupidatat veniam dolor dolor laborum culpa veniam. Quis commodo quis ad enim aute nostrud occaecat. Ipsum excepteur laborum nisi ad laboris anim laborum deserunt duis occaecat fugiat magna.\r\n',
        registered: '2014-02-09T06:52:01 -08:00',
        latitude: -50.415111,
        longitude: -136.212225,
        tags: ['ipsum', 'in', 'nulla', 'consectetur', 'eu', 'dolore', 'tempor'],
        friends: [
          {
            id: 0,
            name: 'Jill Mercado',
          },
          {
            id: 1,
            name: 'Lewis Harding',
          },
          {
            id: 2,
            name: 'Morse Delacruz',
          },
        ],
        greeting: 'Hello, Lily Duran! You have 2 unread messages.',
        favoriteFruit: 'apple',
      },
      {
        _id: '621e13c4fbdd49c31217598e',
        index: 6,
        guid: '2f11f50a-42b1-4c68-8cd0-d08dfdd7f566',
        isActive: false,
        balance: '$1,449.39',
        picture: 'http://placehold.it/32x32',
        age: 33,
        eyeColor: 'green',
        name: 'Felecia Cox',
        gender: 'female',
        company: 'VOIPA',
        email: 'feleciacox@voipa.com',
        phone: '+1 (966) 476-2259',
        address: '584 Oliver Street, Woodruff, Vermont, 2636',
        about:
          'Cillum anim elit non ullamco. Labore voluptate est adipisicing enim. Deserunt fugiat magna adipisicing sint laboris culpa nostrud deserunt incididunt aliqua tempor et. Ullamco nulla incididunt aliqua anim ex culpa dolore voluptate.\r\n',
        registered: '2017-08-29T06:17:27 -08:00',
        latitude: 19.152648,
        longitude: -59.115298,
        tags: [
          'excepteur',
          'tempor',
          'laboris',
          'officia',
          'elit',
          'occaecat',
          'mollit',
        ],
        friends: [
          {
            id: 0,
            name: 'Knox Hester',
          },
          {
            id: 1,
            name: 'Haynes Mcintyre',
          },
          {
            id: 2,
            name: 'Eleanor Hewitt',
          },
        ],
        greeting: 'Hello, Felecia Cox! You have 10 unread messages.',
        favoriteFruit: 'apple',
      },
    ];
    const otherValue = [
      {
        _id: '621e13c4f88a4c8daa76a452',
        index: 0,
        isActive: false,
        balance: '$3,179.17',
        picture: 'http://placehold.it/32x32',
        age: 33,
        eyeColor: 'green',
        name: 'Bettie Cabrera',
        gender: 'female',
        company: 'AUSTEX',
        email: 'bettiecabrera@austex.com',
        phone: '+1 (810) 403-3341',
        address: undefined,
        about:
          'Culpa ullamco ullamco in esse amet consequat sint nulla dolore excepteur in laborum adipisicing eu. Quis dolore aute aliqua eu. Pariatur do irure exercitation incididunt officia cillum eu laborum cupidatat ullamco veniam amet ad minim. Sint deserunt consequat commodo culpa ad. Culpa consectetur incididunt sunt commodo aute amet pariatur proident reprehenderit occaecat. Tempor ex laborum est adipisicing fugiat. Cillum non ad voluptate cupidatat quis pariatur nulla veniam.\r\n',
        registered: '2019-04-06T08:13:50 -08:00',
        latitude: 36.497975,
        longitude: 59.878953,
        tags: [
          'ullamco',
          'Lorem',
          'nostrud',
          'mollit',
          'culpa',
          'minim',
          'tempor',
        ],
        friends: [
          {
            id: 0,
            name: 'Holden Robbins',
          },
          {
            id: 1,
            name: null,
          },
          {
            id: 2,
            name: 'Hendricks Burt',
          },
        ],
        greeting: 'Hello, Bettie Cabrera! You have 3 unread messages.',
        favoriteFruit: 'apple',
      },
      {
        _id: '621e13c4dde1250a88659422',
        index: 1,
        guid: '4b8b0ae2-f263-4258-986b-3d20b866a6b5',
        isActive: true,
        balance: '$1,007.53',
        picture: 'http://placehold.it/32x32',
        age: 34,
        eyeColor: 'green',
        name: 'Kenya Mendoza',
        gender: 'female',
        company: 'COMVEYER',
        email: 'kenyamendoza@comveyer.com',
        phone: '+1 (955) 516-2495',
        address: '242 Reed Street, Woodlake, American Samoa, 1631',
        about:
          'Culpa mollit labore exercitation commodo id. Ex ipsum ut aute tempor anim cupidatat commodo. Reprehenderit ea nostrud Lorem sunt in sunt. In cupidatat esse elit commodo nisi est enim.\r\n',
        registered: '2015-10-19T08:18:38 -08:00',
        latitude: -30.092622,
        longitude: -79.992393,
        tags: ['culpa', 'elit', 'fugiat', 'cillum', 'enim', 'ut', 'ut'],
        friends: [
          {
            id: 0,
            name: false,
          },
          {
            id: 1,
            name: 'Effie Lane',
          },
          {
            id: 2,
            name: 'Terrell Maynard',
          },
        ],
        greeting: 'Hello, Kenya Mendoza! You have 7 unread messages.',
        favoriteFruit: 'strawberry',
      },
      {
        _id: '621e13c4cf89a07343302f7c',
        index: 2,
        guid: '7e0cce8c-f88f-462a-9139-e44174b1bf46',
        isActive: true,
        balance: '$2,782.21',
        picture: 'http://placehold.it/32x32',
        age: 38,
        eyeColor: 'blue',
        name: 'Olivia Russell',
        gender: 'female',
        company: 'BALUBA',
        email: 'oliviarussell@baluba.com',
        phone: '+1 (820) 585-3405',
        address: '908 Ocean Parkway, Morgandale, Hawaii, 4181',
        about:
          'Exercitation sit officia proident ullamco. Proident eu ipsum consectetur anim mollit et quis deserunt ea ullamco irure eu adipisicing. Cillum dolore dolore incididunt proident reprehenderit. Cupidatat aute adipisicing sit voluptate qui est commodo veniam elit. Nisi duis et amet minim proident qui nulla minim sunt incididunt duis fugiat tempor. Consectetur qui nulla non ut exercitation ex tempor officia irure sint minim. Cupidatat dolore nulla enim pariatur aute anim do esse labore.\r\n',
        registered: '2020-04-19T02:12:07 -08:00',
        latitude: -25.314924,
        longitude: -170.391531,
        tags: [
          'labore',
          'cillum',
          'qui',
          'non',
          'proident',
          'consequat',
          'mollit',
        ],
        friends: {},
        greeting: 'Hello, Olivia Russell! You have 10 unread messages.',
        favoriteFruit: 'strawberry',
      },
      {
        _id: '621e13c4d4ead96ad07722c0',
        index: 3,
        guid: 'ba1e829d-600b-4ce2-bf97-52332e2266ba',
        isActive: false,
        balance: '$3,353.54',
        picture: 'http://placehold.it/32x32',
        age: 39,
        eyeColor: 'brown',
        name: 'Ingram Hale',
        gender: 'male',
        company: 'CIRCUM',
        email: 'ingramhale@circum.com',
        test: 1,
        phone: '+1 (866) 416-3109',
        address: '778 Caton Place, Bodega, Alabama, 1410',
        about:
          'Elit et anim sunt adipisicing eiusmod commodo elit. Nisi est duis in quis ipsum et eiusmod sint nulla enim voluptate duis sint. Duis in amet minim eiusmod.\r\n',
        registered: '2020-07-23T03:21:11 -08:00',
        latitude: [76.325808],
        longitude: -130.58796,
        tags: 11,
        friends: [
          {
            id: 0,
            name: 'Reynolds Reid',
          },
          {
            id: 1,
            name: 'Raymond Golden',
          },
          {
            id: 2,
            name: 'Griffith Sampson',
          },
        ],
        greeting: 'Hello, Ingram Hale! You have 4 unread messages.',
        favoriteFruit: 'apple',
      },
      {
        _id: '621e13c4894b86bc5a824d1b',
        index: 4,
        guid: 'b0f9d5e4-bb52-430a-a6d1-768a5a95c586',
        isActive: false,
        balance: '$1,673.38',
        picture: 'http://placehold.it/32x32',
        age: 22,
        eyeColor: 'green',
        name: 'Alvarez Hurst',
        gender: 'male',
        company: 'REPETWIRE',
        email: 'alvarezhurst@repetwire.com',
        phone: '+1 (871) 468-2280',
        address: '831 Riverdale Avenue, Taycheedah, Wyoming, 4433',
        about:
          'Aute duis ex exercitation nisi est tempor est ea aute. Et non velit reprehenderit laboris qui duis exercitation tempor aliquip cupidatat labore. Irure reprehenderit duis consequat adipisicing ex incididunt velit mollit cupidatat consectetur sunt fugiat proident. Duis occaecat laboris aliqua incididunt. Ullamco cupidatat culpa sit proident mollit aute tempor Lorem ullamco enim consequat elit laborum sit. Consectetur irure eu laborum anim consectetur nisi magna quis duis reprehenderit ipsum ut minim incididunt. Officia esse eu ad nostrud eiusmod voluptate aliqua labore mollit cupidatat nostrud elit.\r\n',
        registered: '2021-01-03T09:13:10 -08:00',
        latitude: 53.069786,
        longitude: 69.564384,
        tags: [
          'elit',
          'aliqua',
          'ad',
          'est',
          'reprehenderit',
          'laborum',
          'consectetur',
        ],
        friends: [
          {
            id: 0,
            name: 'Hewitt Hammond',
          },
          {
            id: 1,
            name: 'Sherman Sanchez',
          },
          {
            id: 2,
            name: 'Hess Buck',
          },
        ],
        greeting: 'Hello, Alvarez Hurst! You have 1 unread messages.',
        favoriteFruit: 'apple',
      },
      {
        _id: '621e13c4fbdd49c31217598e',
        index: 6,
        guid: '2f11f50a-42b1-4c68-8cd0-d08dfdd7f566',
        isActive: false,
        balance: '$1,449.39',
        picture: 'http://placehold.it/32x32',
        age: 33,
        eyeColor: 'green',
        name: 'Felecia Cox',
        gender: 'female',
        company: 'VOIPA',
        email: 'feleciacox@voipa.com',
        phone: '+1 (966) 476-2259',
        address: '584 Oliver Street, Woodruff, Vermont, 2636',
        about:
          'Cillum anim elit non ullamco. Labore voluptate est adipisicing enim. Deserunt fugiat magna adipisicing sint laboris culpa nostrud deserunt incididunt aliqua tempor et. Ullamco nulla incididunt aliqua anim ex culpa dolore voluptate.\r\n',
        registered: '2017-08-29T06:17:27 -08:00',
        latitude: 19.152648,
        longitude: -59.115298,
        tags: [
          'excepteur',
          'tempor',
          'laboris',
          'officia',
          'elit',
          'occaecat',
          'mollit',
        ],
        friends: [
          {
            id: 0,
            name: 'Knox Hester',
          },
          {
            id: 1,
            name: 'Haynes Mcintyre',
          },
          {
            id: 2,
            name: 'Eleanor Hewitt',
          },
        ],
        greeting: 'Hello, Felecia Cox! You have 10 unread messages.',
        favoriteFruit: 'apple',
      },
    ];
    const diff = deepDiff(value, otherValue);

    expect(diff).not.toBeUndefined();
    expect(deepMerge(value, diff as Diff)).toEqual(otherValue);
  });
});
